{
 "title": "rat temps 2 (influxql)",
 "time": { "from": "2024-12-14T08:02:35.000Z", "to": "2024-12-14T08:33:35.000Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "distance_avg_zero",
    "query": {
     "query": "Select ts from \n  ( \n    (\n      SELECT time, time::STRING as ts \n      FROM \"gantry\" \n      WHERE \"time\" >= $__timeFrom \n        AND \"time\" <= $__timeTo \n        and extruder_target >1 \n      order by time \n      limit 1\n    )\n    UNION ALL\n    (\n     SELECT 0::TIMESTAMP as time, '${__from:date:iso}' as ts\n    )\n   UNION ALL\n    (\n     SELECT 0::TIMESTAMP as time, '${__to:date:iso}' as ts\n    )\n )"
    }
   },
   {
    "name": "beacon_avg_pre_heat",
    "query": {
     "query": "SELECT AVG(distance) AS average_distance\nFROM \"gantry\"\nWHERE \"time\" >= TO_TIMESTAMP('$distance_avg_zero') - INTERVAL '1 MINUTE'\n  AND \"time\" < TO_TIMESTAMP('$distance_avg_zero')\n  AND distance IS NOT NULL"
    }
   },
   {
    "name": "dti_avg_pre_heat",
    "query": {
     "query": "SELECT AVG(dti_displacement) AS average_distance\nFROM \"gantry\"\nWHERE \"time\" >= TO_TIMESTAMP('$distance_avg_zero') - INTERVAL '1 MINUTE'\n  AND \"time\" < TO_TIMESTAMP('$distance_avg_zero')\n  AND dti_displacement IS NOT NULL"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Test Runs Included",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT RUN, MIN(time) AS time\nFROM \"gantry\"\nWHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo\nGROUP BY RUN\nORDER BY time ASC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Deflection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    \"time\",\n    \"distance\" AS distance_raw,\n    \"dti_displacement\" AS dti_displacement_raw,\n    (\"distance\" - $beacon_avg_pre_heat) AS beacon_change,\n    (\"dti_displacement\" - $dti_avg_pre_heat) AS dti_change\n\nFROM \n    \"gantry\"\nWHERE \n    \"time\" >= $__timeFrom\n    AND \"time\" <= $__timeTo\nORDER BY \n    \"time\";"
    }
   ]
  },
  {
   "title": "Heatblock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "gantry",
     "query": "SELECT RUN, MIN(time) AS time FROM \"gantry\"\nWHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo\nGROUP BY RUN\nORDER BY time ASC\nLIMIT 5",
     "select": [
      [
       { "params": [ "extruder_target" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "extruder_temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "gantry",
     "select": [
      [
       { "params": [ "extruder_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "extruder_pwm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gantry",
     "select": [
      [
       { "params": [ "extruder_pwm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "chamber",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gantry",
     "select": [
      [
       { "params": [ "chamber" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "heatsink_g",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gantry",
     "select": [
      [
       { "params": [ "heatsink_g" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "gantry_left",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "gantry",
     "select": [
      [
       { "params": [ "gantry_left" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "gantry_mid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "gantry",
     "select": [
      [
       { "params": [ "gantry_mid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "heater_bed_temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "gantry",
     "select": [
      [
       { "params": [ "heater_bed_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "beacon_coil",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "gantry",
     "select": [
      [
       { "params": [ "beacon_coil" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}